baseURL = "http://sulavtimilsina.github.io/"
title = "Sulav Timilsina"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
disqusShortname = "sulav-blog"  

[params]
author = "Sulav Timilsina"
description = "Sulav's personal blogging website"
keywords = "blog,developer,personal"
info = ["Machine Learning & Deep Learning Enthusiast", "Reader and Learner"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2019
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []



[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/sulavtimilsina"

#[[params.social]]
#name = "Gitlab"
#icon = "fa fa-2x fa-gitlab"
#weight = 2
#url = "https://gitlab.com/sulavtimilsina"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/Durlav98"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/sulav-timilsina-715873124/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 4
url = "https://medium.com/@sulav.timilsina1999"

[[params.social]]
name = "gmail"
icon = "fa fa-envelope fa-2x"
weight = 5
url = "mailto:sulav.timilsina@outlook.com"
#rel = "alternate"
#type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Resume"
weight = 4
url = "resume/resume.pdf"

[languages.ne]
languageName = ":nepal:"
title = "सुलभ तिमिल्सिना"

[languages.ne.params]
author = "सुलभ तिमिल्सिना"
info = "बुज्दै , भोग्दै र सिक्दै!"
description = ""
keywords = ""

[[languages.ne.menu.main]]
name = "बारेमा"
weight = 1
url = "about/"

[[languages.ne.menu.main]]
name = "ब्लग"
weight = 2
url = "posts/"

#[[languages.ne.menu.main]]
#name = "Projetos"
#weight = 3
#url = "projects/"
